version: "3.9"
services:
  api:
    container_name: courseregister1
    image: courseregister1:latest
    depends_on:
      - db
    ports:
      - "8080:80"
    build:
      dockerfile: Dockerfile
      context: .
  db:
      container_name: postgres
      image: postgres:13.2
      ports:
         - ${DATABASE_PORT}:5433
      environment:
        POSTGRES_USER: ${DATABASE_USER}
        POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        POSTGRES_DB: ${DATABASE_DB}
      volumes:
         - ./pgdata:/var/lib/postgresql/data
volumes:
  pgdata:



