import { TypeOrmModuleOptions } from '@nestjs/typeorm';
export const config: TypeOrmModuleOptions = {
  // type: 'postgres',
  // username: 'postgres',
  // password: 'admin',
  // port: 5432,
  // host: '127.0.0.1',
  // database: 'courseregistration',
  // synchronize: true,
  // autoLoadEntities: true,
  name: 'default',
  type: 'postgres',
  host: process.env.DATABASE_HOST,
  port: Number(process.env.DATABASE_PORT),
  username: process.env.database_user,
  password: process.env.DATABASE_PASSWORD,
  database: process.env.DATABASE_DB,
  synchronize: true,
  dropSchema: false,
  logging: true,
  entities: ['dist/**/*.entity.js'],
};
